### ISSUE TITLE
Assert application crash when WEB Browser cancel request to  OFHTTPServer

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#17]
Program: C:\MinGW\msys\1.0\home\gungravekoga\webzonecreator\fcgizonecreator.exe
File: OFRunLoop.m, Line 441

Expression: queue != nil

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by Midar** [comment]
Hm, I had the same one recently when using ofhttp, but I cannot reproduce. Do you have any way to reproduce?

**Comment by Midar** [comment]
Ok, I think that one I had with ofhttp was related to kqueue sometimes being weird on Mac OS X / FreeBSD, where changes are in some rare, indeterministic cases only applied after the call to kqueue, resulting in objectIsReadyForReading: being called on an object that is no longer being observed, which is now unknown by the run loop. Since Windows does not use kqueue though, this is most likely a separate problem (which is hard to fix, since it's an issue with kqueue on OS X / FreeBSD).

Can you please be more precise on what you did that it happened? Did you call stop on the OFHTTPServer, or did you press cancel in the browser? Can you please describe the steps to reproduce?

**Comment by GunGraveKoga** [comment]
Sorry for my silence. 
>Did you call stop on the OFHTTPServer, or did you press cancel in the browser?
I press cancel in browser address input field
>Can you please describe the steps to reproduce?
I use libdispatch (windows version), for dispatching tasks for my OFHTTPServer
In my AppDelegate has method:
- (void)server:(OFHTTPServer *)server didReceiveRequest:(OFHTTPRequest *)request response:(OFHTTPResponse *)response
{
    
    OFHTTPResponse* wrkResp = [response retain];
    OFHTTPRequest* wrkReq = [request retain];
    OFHTTPServer* wrkServer = server;

    [OFFCGIServer serverLog:@"[FCGI] Dispatch task from %@", [wrkReq remoteAddress]];

    dispatch_async(serverQueue, ^{

        
        OFAutoreleasePool* workPool = [OFAutoreleasePool new];

        [OFFCGIServer serverLog:@"[FCGI] Request:%@ recived on Server: %@ <%@:%zu>\nMethod: %@\nQuery: %@", 
            [[wrkReq URL] path], 
            [server name], 
            [server host], 
            [server port], 
            @(of_http_request_method_to_string([wrkReq method])), 
            (([wrkReq method] == OF_HTTP_REQUEST_METHOD_POST) ? [wrkReq body] : [[wrkReq URL] query])
            ];
        

        OFArray* pathComponents = [[[wrkReq URL] path] pathComponents];
        OFString* firstPathComponent = [pathComponents firstObject];

        if ([firstPathComponent isEqual:@"fcgizone"]) {
            [self performWebzoneActionWithServer:wrkServer forRequest:wrkReq sendResponse:wrkResp];
            
        } else {
            [self performActionWithServer:wrkServer forRequest:wrkReq sendResponse:wrkResp];
        }

        [workPool drain];

    });

}

In browser I connect to URL http://localhost:9000 and after 1 or 1.5 second I press cancel in browser. As result I get application assert-break

**Comment by GunGraveKoga** [comment]
>Hm, I had the same one recently when using ofhttp, but I cannot reproduce. Do you have any way to reproduce? At least a stack trace would be helpful.

Try to reproduce and collect stack trace

**Comment by Midar** [comment]
It might also be interesting to see what you actually do in perform*. Can you please try to strip down as much code as possible to create a test case that I can then run to see what's happening?

**Comment by Midar** [comment]
Closing due to no way to reproduce and lack of feedback.

**Comment by GunGraveKoga** [comment]
OK, it seems I found some additional bug information. If HTTP Client (not OFHTTPClient, simple Internet Browser) break socket connection, and close client-side socket, OFHTTPResponse raise exception when OFHTTPServer delegate try to write data to OFHTTPResponse. If delegate wrap any called OFHTTPResponse method to try/catch, then OFHTTPResponse raise exception on OFHTTPServerResponse::OF_sendHeaders  method, which called on OFHTTPRequest releas.
I collected some backtraces logs with single thread application, with libdispatch (aka. GCD) and with OFThreadPool, also I include in zip archive source for reproducing.
Just uncomment GCD's functions code lines and comment OFThreadPool code lines for switch therebetween, or comment both for single-thread code.


P.S. with OFThreadPool I got some strange behaviour, if client does not break connection to OFHTTPServer, my app raise exception like this:
The selector lock is not understood by an object of type OFTCPSocket

backtrace log included in zip file.
[testcase.zip](https://github.com/Midar/objfw/files/177059/testcase.zip)

**Comment by Midar** [comment]
Thanks for providing further information, but unfortunately, this is far from being usable as a test case: This is almost 900 lines of code! 647 of that are just parsing of cookies and not interacting with OFHTTPServer at all!

Can you please provide a test case? A test case is the *minimal* amount of code required to reproduce the bug. That makes it possible to either demonstrate the bug in ObjFW so that everyone can easily see that in fact there's a bug in ObjFW and not your code or point out if ObjFW is being used the wrong way.

Also, OFHTTPServer is *not* designed to be used with OFThreadPool or libdispatch right now. It is easy to extend it to use multiple threads, but this has not been done yet. So I would not be surprised if this is why things fail. Can you please verify your bug also happens if you run OFHTTPServer in a single OFRunLoop?

If you want OFHTTPServer to provide support for threads, I can add that.

**Comment by GunGraveKoga** [comment]
Yes, problem reproduced with single-threaded OFRunLoop too.
Basic problem is unhandled exception when OFHTTPResponse closing, if OFHTTPServerDelegate does not operates with created OFHTTPresponse.
By default behaviour if OFHTTPResponse headers does not sended before closing, they sends at calling dealloc method, after OFHTTPResponse instanse was released. In this case, if OFTCPSocket throws exception (socket is closed by http client before OFHTTPResponse was released eg.) user cannot catch this exception.

**Comment by GunGraveKoga** [comment]
Multithreading support for OFHTTPServer will be awesome.

**Comment by Midar** [comment]
Hm, on close, it tries to send at least the headers as a reply so that it's possible to just set the status code of the response and then forget about it - it will get released since you never retained it and thus send the response.

The question is now why the write fails. I suppose you keep the response somewhere and did not use it and the other end eventually closes the connection because there's no response? I guess this does not happen anymore if you do not retain it anymore when you will not call write on it anymore?

Maybe it might make things easier to have an explicit method to call to actually send a reply, so that this does not need to be done on dealloc anymore. The disadvantage then though is that you either need to write to it or call this method.

**Comment by Midar** [comment]
Reopening: This was triggered by the bug in the OFKernelEventObserver refactor. But this can still happen in some situations, so I'll reopen to handle possible exceptions there.

**Comment by GunGraveKoga** [comment]
>>>The question is now why the write fails. I suppose you keep the response somewhere and did not use it and the other end eventually closes the connection because there's no response? I guess this does not happen anymore if you do not retain it anymore when you will not call write on it anymore?

No, I does not keep response, I just manually cancel request on client side. By this action I try simulated situation, when client disconnect from server while server preparing response. I try write RESTful-like application, which on some requests doing long time job (download some files, copy those files to specific directories, execute some third-party applications to operate with those files), those actions may take from 5 to 40 minutes. In real life, in this time period many things may happen - client PC power off, or reboot, network problems etc. It will be very sad if server down when try to send response, after all internal works was done...
Also problem compounded by one thing - my application works as NT Service (Windows Service)

>>>Maybe it might make things easier to have an explicit method to call to actually send a reply, so that this does not need to be done on dealloc anymore. The disadvantage then though is that you either need to write to it or call this method.

I think this will be more obviously behaviour for ObjFW users

**Comment by Midar** [comment]
Added another callback to the delegate for this. If it's not implemented by the delegate, such errors will just be ignored.
