### ISSUE TITLE
Error compiling on Linux.

### ISSUE THREAD

**Issue by mralexgray** [Midar/objfw#27]
Fresh clone on ubuntu 14.10...

	OFApplication.m:144:1: error: ivar '_programName' which backs the property is not referenced in this property's accessor [-Werror,-Wunused-property-ivar]
	+ (OFString*)programName
	^
	./OFApplication.h:134:40: note: property declared here
	@property (readonly, assign) OFString *programName;
	                                       ^
	OFApplication.m:149:1: error: ivar '_arguments' which backs the property is not referenced in this property's accessor [-Werror,-Wunused-property-ivar]
	+ (OFArray*)arguments
	^
	./OFApplication.h:139:61: note: property declared here
	@property (readonly, assign) OFArray OF_GENERIC(OFString*) *arguments;
	                                                            ^
	OFApplication.m:154:1: error: ivar '_environment' which backs the property is not referenced in this property's accessor [-Werror,-Wunused-property-ivar]
	+ (OFDictionary*)environment
	^
	./OFApplication.h:145:52: note: property declared here
	    OFDictionary OF_GENERIC(OFString*, OFString*) *environment;
	                                                   ^
	3 errors generated.
	make[3]: *** [OFApplication.lib.o] Error 1
	make[2]: *** [all] Error 2
	make[1]: *** [src] Error 2
	make: *** [all] Error 2

**Comment by Midar** [comment]
This is a bug in the Clang version shipped with Ubuntu 14.10. Please update to a newer Clang version, this will fix it.

**Comment by Midar** [comment]
FWIW, can you try adding `-Wno-unused-property-ivar` to OBJCFLAGS? If that works, I could try to find a test case that triggers this bug and add that to the configure script so it can add that flag.

**Comment by Midar** [comment]
Since the Clang that comes with both Ubuntu 14.04 and 14.10 seems to be affected and thus a significant number of users is hitting this, I added a check to `configure.ac` that checks if the compiler is buggy and if so adds `-Wno-unused-property-ivar`. Old Clang versions get confused if there's a class method with the same name as a property, so the configure script now tries to compile that with -Werror and adds `-Wno-unused-property-ivar` if that fails.
