### ISSUE TITLE
[OFProcess] Windows CreateProcessW return error 87 (The parameter is incorrect.) with nil as environment argument in init method

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#32]
*nix variant of method OF_environmentForDictionary return NULL if environment argument is nil but Windows variant return empty (zero length) null-terminated string

**Comment by Midar** [comment]
Can you please elaborate on the problem? If I pass nil as an argument, it works for me.

**Comment by Midar** [comment]
Hm, interesting, I can reproduce this if I run it in gdb. But otherwise not.

**Comment by Midar** [comment]
Ah, I think I know why: If it is nil, it will create just two zero bytes, but it has to be terminated with 4 zero bytes. As every entry is followed by two zero bytes, the 4 zero bytes for termination are only there if there is at least one entry. When running outside gdb, it just happens that this memory is 0, which is why it works outside of gdb. If the memory is dirty, it also fails outside of gdb. 

I fixed this now.
