### ISSUE TITLE
[OFTCPSocket] OFMemoryNotPartOfObjectException in reused (in case of reconnect) socket

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#33]
Exception thrown if connect to server, read some data, close socket, and then connect to server again

Example in attached file
[socket.zip](https://github.com/Midar/objfw/files/303489/socket.zip)

**Comment by Midar** [comment]
Reusing sockets is not safe. It could be changed in the future, though.

**Comment by GunGraveKoga** [comment]
But what about comment in source code of OFTCPSocket?
/* Make sure to clear the read buffer in case the socket is reused */
	[self freeMemory: _readBuffer];

If I change code at lines 262 & 263 in OFTCPSocket.m to this:

        [self freeMemory: _readBufferMemory];
	_readBuffer = _readBufferMemory = NULL;

That fixes problem with exception

**Comment by Midar** [comment]
No, that does not fix the problem - it will prevent the exception, but it will not make it magically work. All state would need to be reset on -close. I at some time planned to do that, but never followed through with it. Well, shouldn't be much work, so yeah, no point in not doing it.

**Comment by Midar** [comment]
Implemented.

**Comment by GunGraveKoga** [comment]
OK
It's just was surprise for me to get this exception after update to latest commits of ObjFW

**Comment by GunGraveKoga** [comment]
Thanks!

**Comment by Midar** [comment]
Yes, it's understandable that this was a surprise to you :). There was nothing in the documentation stating you cannot do that and the comment looked like it does work. The comment was from a time when I intended do implement this, but never went through with it since it's of limited use. Well, know that there apparently is a use for this (since you use it that way), I just quickly finished that :).
