### ISSUE TITLE
OFFileManger does not remove directories on Win32

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#35]
removeIteamAtPath: method does not delete directories, except files located in that directory
I think ObjFW need to use _wrmdir instead _wremove

Tested on Windows 7SP1/10 with  MinGW-W64 5.3/4.9 mingw_rt ver.4

```objc
#import <ObjFW/ObjFW.h>


int main(int argc, char const *argv[])
{
	OFFileManager* fm = [OFFileManager defaultManager];

	OFString* dir = [fm currentDirectoryPath];
	dir = [dir stringByAppendingPathComponent:@"test_dir"];

	[fm createDirectoryAtPath:dir];

	[fm removeItemAtPath:dir]; //exception Failed to remove item at path C:\MinGW\msys\1.0\home\gungravekoga\test_dir: Permission denied
	return 0;
}
```

**Comment by Midar** [comment]
Oh, interesting. So remove() (or in case of Windows: _wremove()) does not work for directories. I suppose I need to add an extra of_stat() on Windows to see if it is a directory.

**Comment by Midar** [comment]
Seems to be a bug in Windows: The whole intention of remove() instead of unlink() is that remove() is supposed to be able do delete both, files and empty directories. However, Windows seems to think that remove() and unlink() are the same.

However, since there's an of_stat() just before anyway and there already is an if on the type, I changed it to use unlink() / rmdir() instead now.
