### ISSUE TITLE
[Feature Request] extend OFRunLoop flexibility

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#51]
Sometimes we need to add code that must be executed inside OFRunLoop in a special sequence, and very often OFTimer is not the best solution for this, because we can not determine at what stage this code will be executed. OFTimers are always executed before the kernel read / write events, but for the GUI or other personnel some code must be executed before the timers, after the timers and before observing the kernel events and after observing the kernel to interrogate all GUI events.
Perhaps OFRunLoop should be extended by methods, both for target+selectors, and for Blocks of runloop sources (like it was done for timers, which have ability to call object method or Blocks), that will be executed in accordance with flags passed to method, as like Apple done it for CFRunLoop sources  https://developer.apple.com/documentation/corefoundation/cfrunloopactivity?language=objc

In this way we will have ability to execute some code in time of OFRunLoop starts, before Timers runing, before I/O events observing, before waiting to next timer execution time or next iteration, after that waiting, in time of OFRunLoop breakening / termination or in all this cases.

**Comment by Midar** [comment]
I'm not sure what you'd gain by this? The run loop intentionally blocks until the next event - either a timer or I/O. What would you gain by adding something else there? It would still not run before the next timer or I/O event, as the thread is sleeping until then. Do you want it to periodically wake up and check a condition?

**Comment by GunGraveKoga** [comment]
Perhaps, we need another flag for the state of inactivity. For example, an object, call it OFRunLoopObserver created with the start-up order flag, the index (the priority used by sorting the list of observers) and flag of repeat (true/false). When we add an observer to a run loop, this object is added to several sorted lists, one for each flag of the order of the observer's execution. If there are observers in a run loop idle list, the loop cycle executes it periodically, waiting for the next I / O event or timer. Each observer must be executed only if it is still valid, and if the observer is to be repeated, the observer adds self to start the loop again, as is done for OFTimer.

**Comment by GunGraveKoga** [comment]
I think ObjFW user need to have ability to integrate events polling from 3rd party tools like SDL, wxWidgets and others. Usage of OFTimer for manually polling events from that tools is a not a good idea.

**Comment by Midar** [comment]
This is not possible, because this is not how the kernel APIs work. You can watch file descriptors with a timeout. This allows handling I/O and timers. There is no kernel support for anything else, except on macOS, which also supports Mach ports via kqueue.

If you want to integrate SDL or wxWidgets, you would need to get the underlying file descriptors. These can then be wrapped into an object implement -[fileDescriptorForReading], which then allows you to observe them.

Another way is to have a separate thread that does the polling, and then schedules a non-repeating timer with timeout 0 on the originating thread with the run loop. This will make -[observe] immediately return, and the run loop will immediately execute the timer. This is done by having an internal pipe that is used to cancel an -[observe] call, which is then sent a byte so that select() / poll() / kevent() return because a byte is ready to be read.
